version: '3.8'

services:
    dev:
        container_name: nestjs-containerized-dev
        image: nestjs-containerized-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        command: npm run start:debug
        ports:
            - "8080:3000"
        volumes:
            - .:/projects/src/app
            - /projects/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs-containerized-prod
        image: nestjs-containerized-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
        volumes:
            - .:/projects/src/app
            - /projects/src/app/node_modules
        restart: unless-stopped